# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import store_api_pb2 as store__api__pb2


class StoreStub(object):
  """The veracity store service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SaveContract = channel.unary_unary(
        '/store.Store/SaveContract',
        request_serializer=store__api__pb2.ContractRequest.SerializeToString,
        response_deserializer=store__api__pb2.ContractResponse.FromString,
        )


class StoreServicer(object):
  """The veracity store service definition.
  """

  def SaveContract(self, request, context):
    """Sends a greeting.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SaveContract': grpc.unary_unary_rpc_method_handler(
          servicer.SaveContract,
          request_deserializer=store__api__pb2.ContractRequest.FromString,
          response_serializer=store__api__pb2.ContractResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'store.Store', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
