# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='store_api.proto',
  package='store',
  syntax='proto3',
  serialized_pb=_b('\n\x0fstore_api.proto\x12\x05store\".\n\x0f\x43ontractRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\"#\n\x10\x43ontractResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x05Store\x12?\n\x0cSaveContract\x12\x16.store.ContractRequest\x1a\x17.store.ContractResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTRACTREQUEST = _descriptor.Descriptor(
  name='ContractRequest',
  full_name='store.ContractRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='store.ContractRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='store.ContractRequest.owner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=72,
)


_CONTRACTRESPONSE = _descriptor.Descriptor(
  name='ContractResponse',
  full_name='store.ContractResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='store.ContractResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['ContractRequest'] = _CONTRACTREQUEST
DESCRIPTOR.message_types_by_name['ContractResponse'] = _CONTRACTRESPONSE

ContractRequest = _reflection.GeneratedProtocolMessageType('ContractRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTREQUEST,
  __module__ = 'store_api_pb2'
  # @@protoc_insertion_point(class_scope:store.ContractRequest)
  ))
_sym_db.RegisterMessage(ContractRequest)

ContractResponse = _reflection.GeneratedProtocolMessageType('ContractResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTRESPONSE,
  __module__ = 'store_api_pb2'
  # @@protoc_insertion_point(class_scope:store.ContractResponse)
  ))
_sym_db.RegisterMessage(ContractResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class StoreStub(object):
    """The veracity store service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SaveContract = channel.unary_unary(
          '/store.Store/SaveContract',
          request_serializer=ContractRequest.SerializeToString,
          response_deserializer=ContractResponse.FromString,
          )


  class StoreServicer(object):
    """The veracity store service definition.
    """

    def SaveContract(self, request, context):
      """Sends a greeting.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SaveContract': grpc.unary_unary_rpc_method_handler(
            servicer.SaveContract,
            request_deserializer=ContractRequest.FromString,
            response_serializer=ContractResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'store.Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaStoreServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The veracity store service definition.
    """
    def SaveContract(self, request, context):
      """Sends a greeting.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaStoreStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The veracity store service definition.
    """
    def SaveContract(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends a greeting.
      """
      raise NotImplementedError()
    SaveContract.future = None


  def beta_create_Store_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('store.Store', 'SaveContract'): ContractRequest.FromString,
    }
    response_serializers = {
      ('store.Store', 'SaveContract'): ContractResponse.SerializeToString,
    }
    method_implementations = {
      ('store.Store', 'SaveContract'): face_utilities.unary_unary_inline(servicer.SaveContract),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Store_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('store.Store', 'SaveContract'): ContractRequest.SerializeToString,
    }
    response_deserializers = {
      ('store.Store', 'SaveContract'): ContractResponse.FromString,
    }
    cardinalities = {
      'SaveContract': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'store.Store', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
